name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Building - API
        run: yarn build --filter=api
      - name: Building - Staff
        run: yarn build --filter=staff
      - name: Building - App
        run: yarn build --filter=app
      - name: Build Check
        run: yarn build

